import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
	AppBar,
	Toolbar,
	Typography,
	Button,
	Container,
	Box
} from "@mui/material";
import ClientThemeProvider from "@/theme/ClientThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ClientThemeProvider>
					<div
						style={{
							display: "flex",
							flexDirection: "column",
							minHeight: "100vh"
						}}
					>
						<AppBar position="static">
							<Toolbar>
								<Typography
									variant="h6"
									sx={{ flexGrow: 1 }}
								>
									My Developer Portfolio
								</Typography>
								<Button
									color="inherit"
									href="./"
								>
									Home
								</Button>
								<Button
									color="inherit"
									href="projects"
								>
									Projects
								</Button>
								<Button
									color="inherit"
									href="contact"
								>
									Contact
								</Button>
							</Toolbar>
						</AppBar>

						<Container
							maxWidth="lg"
							style={{ flexGrow: 1 }}
						>
							{children}
						</Container>

						<Box
							component="footer"
							sx={{
								py: 3,
								px: 2,
								backgroundColor: "#333",
								color: "white",
								textAlign: "center"
							}}
						>
							<Typography variant="body1">
								&copy; {new Date().getFullYear()} Gerell Troche. All rights
								reserved.{" "}
								<Typography
									variant="caption"
									component="span"
								>
									I may not know them, but I reserve them.
								</Typography>
							</Typography>
						</Box>
					</div>
				</ClientThemeProvider>
			</body>
		</html>
	);
}
